// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserAddReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddReq) Reset()         { *m = UserAddReq{} }
func (m *UserAddReq) String() string { return proto.CompactTextString(m) }
func (*UserAddReq) ProtoMessage()    {}
func (*UserAddReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserAddReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddReq.Unmarshal(m, b)
}
func (m *UserAddReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddReq.Marshal(b, m, deterministic)
}
func (m *UserAddReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddReq.Merge(m, src)
}
func (m *UserAddReq) XXX_Size() int {
	return xxx_messageInfo_UserAddReq.Size(m)
}
func (m *UserAddReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddReq proto.InternalMessageInfo

func (m *UserAddReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserAddReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserAddReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserAddReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type UserAddRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Uid                  uint64   `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddRsp) Reset()         { *m = UserAddRsp{} }
func (m *UserAddRsp) String() string { return proto.CompactTextString(m) }
func (*UserAddRsp) ProtoMessage()    {}
func (*UserAddRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserAddRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddRsp.Unmarshal(m, b)
}
func (m *UserAddRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddRsp.Marshal(b, m, deterministic)
}
func (m *UserAddRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddRsp.Merge(m, src)
}
func (m *UserAddRsp) XXX_Size() int {
	return xxx_messageInfo_UserAddRsp.Size(m)
}
func (m *UserAddRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddRsp proto.InternalMessageInfo

func (m *UserAddRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserAddRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserAddRsp) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserUpdateReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateReq) Reset()         { *m = UserUpdateReq{} }
func (m *UserUpdateReq) String() string { return proto.CompactTextString(m) }
func (*UserUpdateReq) ProtoMessage()    {}
func (*UserUpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserUpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateReq.Unmarshal(m, b)
}
func (m *UserUpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateReq.Marshal(b, m, deterministic)
}
func (m *UserUpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateReq.Merge(m, src)
}
func (m *UserUpdateReq) XXX_Size() int {
	return xxx_messageInfo_UserUpdateReq.Size(m)
}
func (m *UserUpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateReq proto.InternalMessageInfo

func (m *UserUpdateReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserUpdateReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserUpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserUpdateReq) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserUpdateReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UserInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type UserDetail struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetail) Reset()         { *m = UserDetail{} }
func (m *UserDetail) String() string { return proto.CompactTextString(m) }
func (*UserDetail) ProtoMessage()    {}
func (*UserDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetail.Unmarshal(m, b)
}
func (m *UserDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetail.Marshal(b, m, deterministic)
}
func (m *UserDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetail.Merge(m, src)
}
func (m *UserDetail) XXX_Size() int {
	return xxx_messageInfo_UserDetail.Size(m)
}
func (m *UserDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetail.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetail proto.InternalMessageInfo

func (m *UserDetail) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserDetail) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UserDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserDetail) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserDetail) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserDetail) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserInfoReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoReq) Reset()         { *m = UserInfoReq{} }
func (m *UserInfoReq) String() string { return proto.CompactTextString(m) }
func (*UserInfoReq) ProtoMessage()    {}
func (*UserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoReq.Unmarshal(m, b)
}
func (m *UserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoReq.Marshal(b, m, deterministic)
}
func (m *UserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoReq.Merge(m, src)
}
func (m *UserInfoReq) XXX_Size() int {
	return xxx_messageInfo_UserInfoReq.Size(m)
}
func (m *UserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoReq proto.InternalMessageInfo

func (m *UserInfoReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfoReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type UserInfoRsp struct {
	Code                 int64       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User                 *UserDetail `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserInfoRsp) Reset()         { *m = UserInfoRsp{} }
func (m *UserInfoRsp) String() string { return proto.CompactTextString(m) }
func (*UserInfoRsp) ProtoMessage()    {}
func (*UserInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRsp.Unmarshal(m, b)
}
func (m *UserInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRsp.Marshal(b, m, deterministic)
}
func (m *UserInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRsp.Merge(m, src)
}
func (m *UserInfoRsp) XXX_Size() int {
	return xxx_messageInfo_UserInfoRsp.Size(m)
}
func (m *UserInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRsp proto.InternalMessageInfo

func (m *UserInfoRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserInfoRsp) GetUser() *UserDetail {
	if m != nil {
		return m.User
	}
	return nil
}

type UserListReq struct {
	Id                   []uint64 `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListReq) Reset()         { *m = UserListReq{} }
func (m *UserListReq) String() string { return proto.CompactTextString(m) }
func (*UserListReq) ProtoMessage()    {}
func (*UserListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UserListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListReq.Unmarshal(m, b)
}
func (m *UserListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListReq.Marshal(b, m, deterministic)
}
func (m *UserListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListReq.Merge(m, src)
}
func (m *UserListReq) XXX_Size() int {
	return xxx_messageInfo_UserListReq.Size(m)
}
func (m *UserListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserListReq proto.InternalMessageInfo

func (m *UserListReq) GetId() []uint64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type UserListRsp struct {
	Code                 int64       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User                 []*UserInfo `protobuf:"bytes,3,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserListRsp) Reset()         { *m = UserListRsp{} }
func (m *UserListRsp) String() string { return proto.CompactTextString(m) }
func (*UserListRsp) ProtoMessage()    {}
func (*UserListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UserListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRsp.Unmarshal(m, b)
}
func (m *UserListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRsp.Marshal(b, m, deterministic)
}
func (m *UserListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRsp.Merge(m, src)
}
func (m *UserListRsp) XXX_Size() int {
	return xxx_messageInfo_UserListRsp.Size(m)
}
func (m *UserListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRsp proto.InternalMessageInfo

func (m *UserListRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserListRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserListRsp) GetUser() []*UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type Response struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserAddReq)(nil), "user.UserAddReq")
	proto.RegisterType((*UserAddRsp)(nil), "user.UserAddRsp")
	proto.RegisterType((*UserUpdateReq)(nil), "user.UserUpdateReq")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
	proto.RegisterType((*UserDetail)(nil), "user.UserDetail")
	proto.RegisterType((*UserInfoReq)(nil), "user.UserInfoReq")
	proto.RegisterType((*UserInfoRsp)(nil), "user.UserInfoRsp")
	proto.RegisterType((*UserListReq)(nil), "user.UserListReq")
	proto.RegisterType((*UserListRsp)(nil), "user.UserListRsp")
	proto.RegisterType((*Response)(nil), "user.Response")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xcf, 0x4b, 0xeb, 0x40,
	0x10, 0x26, 0x3f, 0x5e, 0x9a, 0x37, 0xe5, 0x95, 0xbe, 0x7d, 0xf0, 0x08, 0x01, 0x41, 0x16, 0x0f,
	0xbd, 0x58, 0xb5, 0x1e, 0xf4, 0xaa, 0x78, 0x11, 0x7a, 0x0a, 0xf4, 0xe2, 0x45, 0xd6, 0xee, 0x2a,
	0x01, 0x9b, 0x6c, 0x33, 0x1b, 0xf5, 0xe6, 0x7f, 0xe1, 0x5f, 0xe5, 0x1f, 0x25, 0xbb, 0x9b, 0x5f,
	0x8d, 0x7a, 0x28, 0x14, 0x6f, 0x33, 0xdf, 0x32, 0xf3, 0x7d, 0xf3, 0x65, 0x26, 0x00, 0x25, 0x8a,
	0x62, 0x2a, 0x8b, 0x5c, 0xe5, 0xc4, 0xd7, 0x31, 0xcd, 0x00, 0x16, 0x28, 0x8a, 0x0b, 0xce, 0x13,
	0xb1, 0x26, 0x11, 0x0c, 0xd8, 0x72, 0x99, 0x97, 0x99, 0x8a, 0x9c, 0x7d, 0x67, 0xf2, 0x3b, 0xa9,
	0x53, 0x12, 0x43, 0x28, 0x19, 0xe2, 0x73, 0x5e, 0xf0, 0xc8, 0x35, 0x4f, 0x4d, 0x4e, 0x08, 0xf8,
	0x19, 0x5b, 0x89, 0xc8, 0x33, 0xb8, 0x89, 0xc9, 0x7f, 0x08, 0xd8, 0x13, 0x53, 0xac, 0x88, 0x7c,
	0x83, 0x56, 0x19, 0x9d, 0xb7, 0x7c, 0x28, 0x75, 0xe5, 0x32, 0xe7, 0xc2, 0x90, 0x79, 0x89, 0x89,
	0xb5, 0x86, 0x95, 0x40, 0x64, 0x0f, 0xa2, 0x22, 0xaa, 0x53, 0x32, 0x06, 0xaf, 0x4c, 0xb9, 0xa1,
	0xf1, 0x13, 0x1d, 0xd2, 0x57, 0xf8, 0xa3, 0xbb, 0x2d, 0x24, 0x67, 0x4a, 0xe8, 0x01, 0x46, 0xe0,
	0xa6, 0xdc, 0xb4, 0xf3, 0x13, 0x37, 0xe5, 0xbb, 0x92, 0xad, 0x71, 0x54, 0x4c, 0x95, 0x18, 0xfd,
	0xb2, 0xb8, 0xcd, 0xe8, 0x0b, 0x84, 0x5a, 0xc0, 0x75, 0x76, 0x9f, 0x7f, 0xe2, 0xee, 0x98, 0xe9,
	0x6e, 0x9a, 0xb9, 0x0b, 0xe6, 0x37, 0xc7, 0x3a, 0x79, 0x25, 0x14, 0x4b, 0x1f, 0x7f, 0x96, 0x7c,
	0xc3, 0xd6, 0x60, 0xd3, 0x56, 0x7a, 0x06, 0xc3, 0xda, 0x92, 0xaf, 0xbe, 0xc8, 0xb7, 0xc2, 0x28,
	0xeb, 0x14, 0x6e, 0xbd, 0x1b, 0x07, 0x60, 0xf6, 0xd9, 0x4c, 0x35, 0x9c, 0x8d, 0xa7, 0x66, 0xd1,
	0x5b, 0x7f, 0x12, 0xbb, 0xed, 0x7b, 0x96, 0x62, 0x9e, 0xa2, 0xea, 0x6a, 0xf3, 0xac, 0x36, 0x7a,
	0xdb, 0x79, 0xde, 0x5a, 0x01, 0x6d, 0x14, 0x78, 0x93, 0xe1, 0x6c, 0xd4, 0x2a, 0x30, 0x03, 0x59,
	0xfe, 0x73, 0x08, 0x13, 0x81, 0x32, 0xcf, 0x50, 0x6c, 0xd7, 0x7d, 0xf6, 0xee, 0x80, 0xaf, 0x9b,
	0x91, 0x43, 0x18, 0x54, 0x07, 0x44, 0x3a, 0x53, 0xda, 0xfb, 0x8d, 0x7b, 0x08, 0x4a, 0x72, 0x62,
	0xb7, 0xc4, 0x5e, 0x08, 0xf9, 0xd7, 0xbe, 0x37, 0x37, 0x13, 0x57, 0x52, 0x1b, 0x61, 0xc7, 0x9d,
	0x9d, 0xfe, 0xdb, 0x1b, 0x43, 0xac, 0xe3, 0x3e, 0x84, 0xb2, 0xae, 0xd0, 0xbe, 0x75, 0x2b, 0x2a,
	0x9b, 0xe3, 0x3e, 0x84, 0xf2, 0x32, 0xbc, 0x09, 0xa6, 0x47, 0x1a, 0xbd, 0x0b, 0xcc, 0xdf, 0xe8,
	0xf4, 0x23, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x1a, 0xed, 0x66, 0x9b, 0x04, 0x00, 0x00,
}
