// Code generated by goctl. DO NOT EDIT!
// Source: main.proto

package user

import (
	"context"

	"github.com/acger/user-svc/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Response      = user.Response
	UserAddReq    = user.UserAddReq
	UserAddRsp    = user.UserAddRsp
	UserDetail    = user.UserDetail
	UserInfo      = user.UserInfo
	UserInfoReq   = user.UserInfoReq
	UserInfoRsp   = user.UserInfoRsp
	UserListReq   = user.UserListReq
	UserListRsp   = user.UserListRsp
	UserUpdateReq = user.UserUpdateReq

	User interface {
		UserAdd(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*UserAddRsp, error)
		UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*Response, error)
		UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRsp, error)
		UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListRsp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) UserAdd(ctx context.Context, in *UserAddReq, opts ...grpc.CallOption) (*UserAddRsp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserAdd(ctx, in, opts...)
}

func (m *defaultUser) UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*Response, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserUpdate(ctx, in, opts...)
}

func (m *defaultUser) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoRsp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

func (m *defaultUser) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListRsp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}
