name: Go

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: build image
      env:
        REP: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
      run: |
        docker build -t $REP .
        docker push $REP
    
    - name: deploy to ask
      uses: aliyun/ack-set-context@v1
      with:
        access-key-id: "${{ secrets.ASK_ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ASK_ACCESS_KEY_SECRET }}"
        cluster-id: "${{ secrets.ASK_CLUSTER_ID }}"

    - name: Deploy
      run: |
        kubectl apply -f cd.yaml
        kubectl get services -o wide
    
      
